name: Unity CI Pipeline

on: 
    push: 
        branches:
            - Build-Branch 
    workflow_dispatch:
env:
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

jobs:
  buildWindows:
    name: Build for Windows 🖥️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-build-StandaloneWindows64
          restore-keys: |
            Library-build-
            Library-
     
      - name: Build Unity
        id: unityBuild
        uses: game-ci/unity-builder@v2   
        with:
          targetPlatform: Android


      - name: Upload build to itch.io 
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/Android
          project: n0tlucifer/polar-penguin-rush
          channel: win
          version: ${{ steps.unityBuild.outputs.buildVersion}}
          api-key: ${{ secrets.ITCH_API_KEY }}
   
 
      - name: Discord notification
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_STUDIO23 }}
        uses: Ilshidur/action-discord@master
        with:
            args: 'Polar Penguin Rush built and has been deployed at https://n0tlucifer.itch.io/polar-penguin-rush'
